name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  detect-drift:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode || true

      - name: Check Drift Result
        run: |
          if [ "${{ steps.plan.outputs.exitcode }}" == "2" ]; then
            echo "Drift detected!"
            exit 1
          else
            echo "No drift detected."
          fi
